global:
  smtp_from: 'parkjongwon127@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'parkjongwon127@gmail.com'
  smtp_auth_identity: 'parkjongwon127@gmail.com'
  smtp_auth_password: 'xcnsibbrdotxgixo'

route:
# fallback receiver
  receiver: admin
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes:
  # Star solutions
  - match_re: 
      app_type: (linux|windows)
    receiver: ss-admin
    routes:
    # Linux team
    - match:
        app_type: linux
    # fallback receiver
      receiver: linux-team-admin
      group_by: [category]
      routes:
      - match:
          severity: critical
        receiver: linux-team-manager
        # continue: true
      - match:
          severity: warning
        receiver: linux-team-lead
      # - match:
      #     category: cpu
      #   receiver: linux-cpu-person
          
    # # Windows team
    # - match:
    #     app_type: windows
    # # fallback receiver
    #   receiver: windows-team-admin
    #   routes:
    #   - match:
    #       severity: critical
    #     receiver: windows-team-manager
    #   - match:
    #       severity: warning
    #     receiver: windows-team-lead

  # PEC technologies
  - match_re: 
      app_type: (python|go)
    receiver: pt-admin
    routes:
    # python team
    - match:
        app_type: python
    # fallback receiver
      receiver: python-team-admin
      routes:
      - match:
          severity: critical
        receiver: python-team-manager
      - match:
          severity: warning
        receiver: python-team-lead
          
    # # go team
    # - match:
    #     app_type: go
    # # fallback receiver
    #   receiver: go-team-admin
    #   routes:
    #   - match:
    #       severity: critical
    #     receiver: go-team-manager
    #   - match:
    #       severity: warning
    #     receiver: go-team-lead

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['app_type', 'category']

receivers:
- name: admin
  email_configs:
  - to: 'harrisonford@daum.net'

- name: ss-admin
  email_configs:
  - to: 'izam8311@naver.com'

- name: linux-team-admin
  email_configs:
  - to: 'izam8311@naver.com'

- name: linux-team-manager
  # email_configs:
  # - to: 'izam8311@naver.com'
  slack_configs:
  - channel: 'prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'Node exporter is down'
    text: 'Node exporter is down for more than 2 minutes'

- name: linux-team-lead
  email_configs:
  - to: 'izam8311@naver.com'

- name: pt-admin
  email_configs:
  - to: 'harrisonford@daum.net'

- name: python-team-admin
  email_configs:
  - to: 'harrisonford@daum.net'

- name: python-team-manager
  email_configs:
  - to: 'harrisonford@daum.net'

- name: python-team-lead
  email_configs:
  - to: 'harrisonford@daum.net'